# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2024-present ISB-emoji contributors

version = 1

[[annotations]]
path = "free/twemoji/**"
SPDX-FileCopyrightText = [
    "2024-present ISB-emoji contributors",
    "2022-present Jason Sofonia & Justine De Caires",
    "2014-2021 Twitter",
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "free/emojitwo/**"
SPDX-FileCopyrightText = [
    "2024-present ISB-emoji contributors",
    "2014-2016 Ranks.com and Emojione contributors",
    "2016-present Emojitwo contributors",
]
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "nonfree/bluemoji/**"
SPDX-FileCopyrightText = [
    "2009-2023 Bluemoji.io",
]
SPDX-License-Identifier = "LicenseRef-Bluemoji"
